### ISSUE TITLE
Issues WIP

### ISSUE THREAD

**Issue by SuBZoiD** [FTBTeam/FTB-Ultimate-Reloaded#362]
### Thank you FTB team for your amazing efforts!

I'm an Ultimate Reloaded server admin that has been playing this Modpack for more than a year now, and since the last update, I have made many observations on issues that can be fixed/tweaked.

This version of the Modpack has been around for a while now, although many players are extremely enjoying it for now, i truly believe its time for an update!

* **Modpack Version**: v1.9.0

### Below is a list of my observations , some of which are already open issues listed on Github.

- [x] Tech Reborn: Superconductor cables not available in JEI, even though they're functional but currently spam the console badly. #287 #199 #137 #122  `Tile techreborn.tiles.cable.TileCableEU@43c89f37 (dim 0: 2810/100/1583), sub tile techreborn.tiles.cable.TileCableEU@43c89f37 (dim 0: 2810/100/1583) addition is conflicting with a previous registration at the same location: TileCableEU{tileType=techreborn:cable_eu, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld}, pos=BlockPos{x=2810, y=100, z=1583}, blockMetadata=8}.`

- [x] Tech Reborn: The fusion reactor has an output limit of 8192 EU/t, even when the limit is fixed from the script, it can only reach the maximum of 32k EU/t (similar to ADSU) #344 #223 

- [ ] Tech Reborn: The ADSU outputs a maximum of 32k EU/t even with 4 superconductor upgrades

- [x] Tech Reborn: basic and advanced machine frames are currently not craftable, although needed to craft the superconductor cable
- [ ] Tech Reborn: Rolling machines induce TPS drops generating an enormous amount of tick delay

- [ ] Tech Reborn: Interdimentional SU is shared between all players, rendering it useless on servers.

- [x] Thaumcraft: Thaumic tinkerer is still in alpha, and not research able yet. although functional in creative

- [x] Immersive Engineering: Any plans to enable this mod? #345 

- [x] IC2/Tech Reborn: Some UU recipes are not working properely #336 

The list goes on and on but the main point is, Ultimate Reloaded fans have been loyal to this Modpack for so long now, and they do deserve their update.

Again, thank you for this amazing Modpack 😄 
@tfox83 @Gaz492 @LatvianModder @modmuss50 @SnowShock35

**Comment by 016Nojr** [comment]
1. Will look into this
2. As stated in #223 "At this time they are not intended for this pack as they transfer RF only."
3. Will look into this
4. Will add a converter between TR and IC2 frames
5. Will look into this, do you have some profiling or any results you can share?
6. Will look into this
7. Thaumic Tinkerer is updated to beta
8. No, it will stay as it is now, but I'll look into disabling all of its machine recipes
9. Will look into this

**Comment by 016Nojr** [comment]
The last 3 unchecked boxes will unfortunately have to stay as it is, unless it's fixed by the pack update that's coming in a few days. The mod isnt recieving any updates for 1.12 anymore
